version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"

  postgres:
    image: "postgres:14"
    container_name: "support_db"
    restart: always
    env_file: ".env"
    # ports:
    #   - "5433:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    command: sh -c "python src/manage.py makemigrations &&
                    python src/manage.py migrate &&
                    python src/manage.py initiate_admin &&
                    python src/manage.py collectstatic &&
                    gunicorn src.config.wsgi:application --bind 0.0.0.0:8000"
    image: "support_app"
    container_name: "support_app"
    env_file:
    - ".env"
    depends_on:
      - "postgres"
    volumes:
      - ".:/app/"
    ports:
      - "8000:8000"

volumes:
  pg_data: {}
