version: "3.9"

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432

volumes:
  postgres_data:
