# Generated by Django 4.1.4 on 2023-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customusers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
    ]
