# Generated by Django 4.1.4 on 2022-12-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                blank=True, default="----", max_length=100, verbose_name="місто"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, default="----", max_length=100, verbose_name="країна"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal",
            field=models.IntegerField(
                blank=True, default="0000", verbose_name="поштова адреса"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="home_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="users.address",
                verbose_name="Домашня адреса",
            ),
        ),
    ]
